import 'reflect-metadata';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AppLayout from "@/components/layout/AppLayout";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import Navbar from "@/components/navigation/Navbar";
import { AppLoading } from "@/components/AppLoading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();
  if (!session) redirect("/login");

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppLayout>
          {/* Passamos a Navbar aqui dentro. 
            Para o AppLayout, isso é apenas 'children'.
          */}
          <Navbar /> 
          
          <main 
            className="flex-grow p-4 pt-20 card-theme layout-transition "
            style={{ marginLeft: 'var(--sidebar-width)' }}
          >
            <div className="bg-white dark:bg-[#1e1e1e] rounded-xl shadow-sm p-6 theme-sync">
              <AppLoading />
              {children}
            </div>
          </main>
        </AppLayout>
      </body>
    </html>
    
  );
}